name: Create Illustration Overview
on:
  push:
    branches:
      - main
    paths:
      - Assets/Illustrations/**

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: Assets/Illustrations/create_illustration_page
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Illustration Page
        working-directory: Assets/Illustrations/create_illustration_page
        run: |
          python ./create_illustration_page.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Assets/Illustrations